sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "5"
  - "4.1"
  - "4.0"
before_script:
  - npm install react react-dom
script:
  - npm run lint
  - npm test
  - npm run build
  - npm run build:examples
